export type TopicCategory = {
  name: string;
  icon: string;
  color: string;
  topics: string[];
};

export const TOPIC_CATEGORIES: TopicCategory[] = [
  {
    name: "Salvation & Grace",
    icon: "✝",
    color: "#f59e0b",
    topics: [
      "John 3:16 — For God So Loved the World",
      "Romans 10:9 — Confessing with Your Mouth",
      "Ephesians 2:8-9 — Saved by Grace Through Faith",
      "Acts 2:38 — Repentance and Baptism",
      "Titus 3:5 — Not by Works but by Mercy",
      "Romans 5:1 — Justified by Faith",
      "2 Corinthians 5:17 — A New Creation",
      "John 1:12 — Becoming Children of God",
      "Romans 6:23 — The Gift of Eternal Life",
      "Galatians 2:20 — Crucified with Christ",
      "The Prodigal Son Returns",
      "What Does It Mean to Be Born Again",
      "The Blood of Jesus",
      "Grace That Is Greater Than All Our Sin",
      "The Cross — What It Cost and What It Won",
      "Redemption — Bought with a Price",
      "Justification by Faith Alone",
      "The Thief on the Cross",
      "No Condemnation in Christ Jesus",
      "Saved to Serve",
    ],
  },
  {
    name: "Faith & Trust",
    icon: "🛡",
    color: "#3b82f6",
    topics: [
      "Hebrews 11:1 — Faith Is the Substance",
      "Matthew 17:20 — Faith as a Mustard Seed",
      "Romans 10:17 — Faith Comes by Hearing",
      "James 2:17 — Faith Without Works Is Dead",
      "Proverbs 3:5-6 — Trust in the Lord",
      "Mark 11:24 — Whatever You Ask in Prayer",
      "2 Corinthians 5:7 — Walk by Faith Not Sight",
      "Habakkuk 2:4 — The Just Shall Live by Faith",
      "Matthew 14:22-33 — Walking on Water",
      "Daniel 3 — The Fiery Furnace",
      "When Faith Is Tested",
      "Trusting God in the Waiting",
      "Faith That Moves Mountains",
      "Stepping Out Before You See",
      "Abraham — Father of Faith",
      "Doubt vs Unbelief",
      "Faith in the Storm",
      "The Shield of Faith",
      "Persistent Faith — The Woman Who Would Not Give Up",
      "What God Can Do With a Little Faith",
    ],
  },
  {
    name: "Prayer & Worship",
    icon: "🙏",
    color: "#8b5cf6",
    topics: [
      "Matthew 6:9-13 — The Lord's Prayer",
      "Philippians 4:6-7 — Prayer and Peace",
      "James 5:16 — The Prayer of a Righteous Man",
      "1 Thessalonians 5:17 — Pray Without Ceasing",
      "John 4:24 — Worship in Spirit and Truth",
      "Psalm 100 — Enter His Courts with Praise",
      "Romans 8:26 — The Spirit Helps Us Pray",
      "Luke 18:1-8 — The Persistent Widow",
      "Psalm 34:1 — I Will Bless the Lord at All Times",
      "Revelation 5:8 — Our Prayers as Incense",
      "Fasting and Prayer",
      "Intercession — Standing in the Gap",
      "Praise as a Weapon",
      "The Secret Place of Prayer",
      "Worshipping Through the Wilderness",
      "Thanksgiving as a Lifestyle",
      "When God Seems Silent",
      "Corporate Prayer and Agreement",
      "The Power of the Name of Jesus in Prayer",
      "Praying the Scriptures",
      "Midnight Praise — Paul and Silas",
      "Waiting on God",
    ],
  },
  {
    name: "Holy Spirit",
    icon: "🔥",
    color: "#ef4444",
    topics: [
      "Acts 2:1-4 — The Day of Pentecost",
      "John 14:16-17 — The Comforter Has Come",
      "Galatians 5:22-23 — The Fruit of the Spirit",
      "1 Corinthians 12 — Gifts of the Spirit",
      "Romans 8:11 — The Spirit That Raised Jesus",
      "Ephesians 5:18 — Be Filled with the Spirit",
      "John 16:13 — The Spirit of Truth",
      "Acts 1:8 — Power to Be Witnesses",
      "Isaiah 61:1 — The Spirit of the Lord Is Upon Me",
      "Romans 8:26 — Intercession of the Spirit",
      "Yielding to the Holy Spirit",
      "The Baptism of the Holy Spirit",
      "Grieving the Holy Spirit",
      "Walking in the Spirit Daily",
      "Tongues, Prophecy and Spiritual Gifts",
      "The Holy Spirit as Teacher",
      "Fire of God — Purification and Power",
      "Sensitivity to the Spirit",
      "Wind and Fire — Symbols of the Spirit",
      "The Spirit of Adoption",
    ],
  },
  {
    name: "Purpose & Calling",
    icon: "🌟",
    color: "#10b981",
    topics: [
      "Jeremiah 29:11 — Plans to Prosper You",
      "Romans 8:28 — All Things Work Together",
      "Ephesians 2:10 — Created for Good Works",
      "Proverbs 19:21 — Purpose in the Lord's Counsel",
      "Isaiah 43:1 — Called by Name",
      "Psalm 139:13-16 — Fearfully and Wonderfully Made",
      "Matthew 22:14 — Many Are Called, Few Are Chosen",
      "Galatians 1:15 — Set Apart Before Birth",
      "1 Peter 2:9 — A Royal Priesthood",
      "John 15:16 — Chosen to Bear Fruit",
      "Discovering Your God-Given Assignment",
      "When Your Calling Feels Too Big",
      "The Wilderness Before the Promise",
      "Joseph — The Dream That Wouldn't Die",
      "Moses — The Reluctant Leader",
      "Esther — Born for Such a Time as This",
      "Gideon — The Unlikely Warrior",
      "Running Your Race with Endurance",
      "Seasons of Preparation",
      "Don't Despise Small Beginnings",
      "Your Gifts Will Make Room for You",
    ],
  },
  {
    name: "Healing & Deliverance",
    icon: "🕊",
    color: "#06b6d4",
    topics: [
      "Isaiah 53:5 — By His Stripes We Are Healed",
      "James 5:14-15 — Anointing with Oil",
      "Matthew 8:17 — He Took Our Infirmities",
      "Psalm 103:3 — Who Heals All Your Diseases",
      "Mark 16:17-18 — Signs That Follow Believers",
      "Luke 4:18 — He Has Sent Me to Heal",
      "Acts 3:1-10 — Rise Up and Walk",
      "John 5:1-15 — The Pool of Bethesda",
      "Luke 17:11-19 — The Ten Lepers",
      "3 John 1:2 — Prosper and Be in Health",
      "Healing Is God's Will",
      "Emotional and Inner Healing",
      "Breaking Generational Curses",
      "Freedom from Addiction",
      "Mental Health and the Peace of God",
      "The Woman with the Issue of Blood",
      "Deliverance from Fear and Anxiety",
      "Restoration After Trauma",
      "Wholeness — Spirit, Soul, and Body",
      "The Ministry of Laying On of Hands",
    ],
  },
  {
    name: "Relationships & Family",
    icon: "❤",
    color: "#ec4899",
    topics: [
      "1 Corinthians 13 — The Love Chapter",
      "Ephesians 5:22-33 — Marriage God's Way",
      "Proverbs 22:6 — Train Up a Child",
      "Colossians 3:13 — Forgive As the Lord Forgave",
      "Matthew 18:21-22 — Seventy Times Seven",
      "Ephesians 6:1-4 — Children and Parents",
      "Ruth 1:16 — Where You Go I Will Go",
      "Ecclesiastes 4:9-10 — Two Are Better Than One",
      "1 Peter 4:8 — Love Covers Many Sins",
      "Proverbs 31 — A Woman of Noble Character",
      "Godly Marriage in a Broken World",
      "Raising Children in the Fear of God",
      "Forgiveness — Releasing What You Cannot Change",
      "Healthy Boundaries in Christian Relationships",
      "Friendship — Iron Sharpening Iron",
      "Healing After Divorce",
      "Honouring Your Parents",
      "Love Your Neighbour",
      "The Ministry of Reconciliation",
      "Community — We Were Not Made to Be Alone",
      "Mentorship — Elijah and Elisha",
    ],
  },
  {
    name: "Spiritual Warfare",
    icon: "⚔",
    color: "#f97316",
    topics: [
      "Ephesians 6:10-18 — The Full Armour of God",
      "2 Corinthians 10:4 — Weapons Not Carnal",
      "James 4:7 — Resist the Devil",
      "1 Peter 5:8 — Your Adversary the Devil",
      "Revelation 12:11 — Overcame by the Blood",
      "Luke 10:19 — Authority Over the Enemy",
      "Romans 16:20 — God Will Crush Satan",
      "Matthew 4:1-11 — Jesus and the Temptation",
      "Daniel 10 — The Battle in the Heavens",
      "Isaiah 54:17 — No Weapon Formed Against You",
      "Standing Firm When the Enemy Attacks",
      "The Battle for Your Mind",
      "Pulling Down Strongholds",
      "Spiritual Discernment",
      "Guarding the Gates",
      "The Enemy's Strategies Against Destiny",
      "Intercession as Warfare",
      "Breaking the Power of the Occult",
      "Victory Is Already Won",
      "Fear — The Enemy's Favourite Weapon",
    ],
  },
  {
    name: "Kingdom of God",
    icon: "👑",
    color: "#7c3aed",
    topics: [
      "Matthew 6:33 — Seek First the Kingdom",
      "Luke 17:21 — The Kingdom Is Within You",
      "Mark 1:15 — The Kingdom of God Is at Hand",
      "Matthew 13 — Parables of the Kingdom",
      "Daniel 2:44 — An Everlasting Kingdom",
      "Revelation 11:15 — The Kingdom of Our Lord",
      "Isaiah 9:7 — Of His Government No End",
      "Matthew 5:3-12 — The Beatitudes",
      "Romans 14:17 — Righteousness, Peace and Joy",
      "John 18:36 — My Kingdom Is Not of This World",
      "Kingdom Culture vs World Culture",
      "Advancing the Kingdom in Your Workplace",
      "The Kingdom Belongs to Such as These",
      "Jesus the King — Palm Sunday",
      "Thy Kingdom Come — Praying for Revival",
      "Kingdom Economics — Giving and Receiving",
      "Signs and Wonders as Kingdom Evidence",
      "The Upside Down Kingdom",
      "Discipleship — Making Kingdom Citizens",
      "The Return of the King",
    ],
  },
  {
    name: "Overcoming & Perseverance",
    icon: "💪",
    color: "#059669",
    topics: [
      "Romans 8:37 — More Than Conquerors",
      "James 1:2-4 — Count It All Joy",
      "Philippians 4:13 — I Can Do All Things",
      "2 Timothy 4:7 — I Have Fought the Good Fight",
      "Isaiah 40:31 — Those Who Wait on the Lord",
      "Revelation 2:7 — To Him Who Overcomes",
      "Romans 5:3-5 — Suffering Produces Perseverance",
      "Hebrews 12:1-2 — Run the Race",
      "Psalm 46:1 — God Is Our Refuge and Strength",
      "John 16:33 — In This World You Will Have Trouble",
      "Surviving the Wilderness Season",
      "Don't Quit Before Your Breakthrough",
      "Pressing Through Pain",
      "Job — Holding On When Everything Is Gone",
      "David and Goliath",
      "Nehemiah — Building Despite Opposition",
      "The Valley of the Shadow of Death",
      "When You Feel Like Giving Up",
      "Turning Your Test into a Testimony",
      "The Other Side of the Storm",
      "Paul in Prison — Rejoicing in Chains",
    ],
  },
  {
    name: "Identity in Christ",
    icon: "🏆",
    color: "#b45309",
    topics: [
      "Romans 8:17 — Heirs with Christ",
      "Galatians 3:28 — All Are One in Christ",
      "2 Corinthians 5:21 — The Righteousness of God",
      "John 15:15 — No Longer Servants but Friends",
      "Ephesians 1:4-5 — Chosen and Adopted",
      "Colossians 3:3 — Hidden with Christ in God",
      "1 John 3:1 — See What Love — Called Children of God",
      "Romans 8:1 — No Condemnation",
      "Psalm 8:4-5 — Crowned with Glory and Honour",
      "Isaiah 62:3 — A Crown of Glory",
      "You Are Not Who They Said You Were",
      "Overcoming the Orphan Spirit",
      "Knowing Who You Are in Christ",
      "Breaking the Shame Cycle",
      "Beloved — The Identity Jesus Gives",
      "From Slave to Son",
      "What the Father Says About You",
      "Imposter Syndrome and the Believer",
      "You Are Enough in Christ",
      "Walking in Kingdom Authority",
    ],
  },
  {
    name: "Generosity & Stewardship",
    icon: "💰",
    color: "#16a34a",
    topics: [
      "Malachi 3:10 — Test Me in the Tithe",
      "Luke 21:1-4 — The Widow's Two Mites",
      "2 Corinthians 9:7 — A Cheerful Giver",
      "Proverbs 11:24-25 — Scattering and Increasing",
      "Matthew 25:14-30 — Parable of the Talents",
      "Luke 12:48 — To Whom Much Is Given",
      "Deuteronomy 8:18 — Power to Create Wealth",
      "Acts 4:34-35 — No One Was in Need",
      "Luke 6:38 — Give and It Shall Be Given",
      "1 Timothy 6:17-19 — Command the Rich",
      "Sowing and Reaping",
      "Managing What God Has Given You",
      "Why Christians Should Be Generous",
      "The Danger of the Love of Money",
      "Kingdom Finances",
      "Firstfruits — Honouring God First",
      "Prosperity with Purpose",
      "Contentment in Every Season",
      "The Ministry of Giving",
      "Using Your Resources to Build the Kingdom",
    ],
  },
  {
    name: "The Word of God",
    icon: "📖",
    color: "#0284c7",
    topics: [
      "Psalm 119:105 — A Lamp to My Feet",
      "Hebrews 4:12 — The Word Is Living and Active",
      "John 1:1 — In the Beginning Was the Word",
      "2 Timothy 3:16-17 — All Scripture Is God-Breathed",
      "Isaiah 55:11 — My Word Shall Not Return Void",
      "Matthew 4:4 — Man Does Not Live by Bread Alone",
      "Romans 10:17 — Faith Comes by Hearing",
      "Joshua 1:8 — Meditate on It Day and Night",
      "Proverbs 30:5 — Every Word of God Is Pure",
      "Jeremiah 15:16 — Your Word Was My Joy",
      "Rightly Dividing the Word of Truth",
      "Hiding the Word in Your Heart",
      "The Bible — God's Love Letter to Humanity",
      "Logos and Rhema — The Written and Spoken Word",
      "Preaching the Word in Season and Out of Season",
      "How to Study the Bible",
      "The Power of Declaring the Word",
      "Eating the Word — Spiritual Nourishment",
      "When God Speaks Personally to You",
      "Standing on the Promises",
    ],
  },
  {
    name: "Evangelism & Mission",
    icon: "🌍",
    color: "#0891b2",
    topics: [
      "Matthew 28:19-20 — The Great Commission",
      "Acts 1:8 — You Shall Be My Witnesses",
      "Romans 1:16 — Not Ashamed of the Gospel",
      "Mark 16:15 — Go into All the World",
      "Isaiah 6:8 — Here Am I, Send Me",
      "Luke 15:4-7 — The Lost Sheep",
      "John 4:1-42 — The Woman at the Well",
      "Acts 8:26-40 — Philip and the Ethiopian",
      "Romans 10:14-15 — How Shall They Hear",
      "2 Corinthians 5:20 — Ambassadors for Christ",
      "Personal Evangelism — Your Testimony",
      "Missions — Reaching the Unreached",
      "Marketplace Ministry",
      "One Soul Is Worth It All",
      "Living the Gospel — Lifestyle Evangelism",
      "Boldness in Sharing Your Faith",
      "The Harvest Is Plentiful",
      "Urban Ministry",
      "Youth Outreach",
      "The Church's Role in Social Justice",
    ],
  },
  {
    name: "Character & Holiness",
    icon: "⚡",
    color: "#a21caf",
    topics: [
      "1 Peter 1:16 — Be Holy As I Am Holy",
      "Romans 12:1-2 — Living Sacrifices",
      "Galatians 5:16-17 — Walk in the Spirit",
      "Proverbs 4:23 — Guard Your Heart",
      "Matthew 5:8 — Blessed Are the Pure in Heart",
      "Psalm 51 — Create in Me a Clean Heart",
      "2 Chronicles 7:14 — If My People Humble Themselves",
      "Micah 6:8 — Justice, Mercy, Humility",
      "Philippians 4:8 — Think on These Things",
      "Romans 13:14 — Put on Christ",
      "Integrity When No One Is Watching",
      "The Danger of a Double Life",
      "Humility — The Foundation of Greatness",
      "Sexual Purity in a Fallen World",
      "Taming the Tongue",
      "Anger — Don't Sin in Your Anger",
      "Repentance — More Than Sorry",
      "Accountability in the Christian Life",
      "Sanctification — The Ongoing Process",
      "The Fear of the Lord",
    ],
  },
  {
    name: "Resurrection & Eternity",
    icon: "✨",
    color: "#f59e0b",
    topics: [
      "John 11:25 — I Am the Resurrection and the Life",
      "1 Corinthians 15:55 — Death Where Is Your Sting",
      "Revelation 21:1-5 — All Things New",
      "Romans 6:4-5 — Raised to Walk in New Life",
      "Philippians 3:20-21 — Our Citizenship Is in Heaven",
      "2 Corinthians 5:1 — Eternal House in Heaven",
      "John 14:2-3 — I Go to Prepare a Place",
      "1 Thessalonians 4:16-17 — The Rapture",
      "Revelation 20:11-15 — The Great White Throne",
      "Acts 1:11 — This Same Jesus Will Return",
      "Easter — He Is Risen",
      "Living with Eternity in View",
      "Heaven — What the Bible Actually Says",
      "The Second Coming of Christ",
      "Grief and Christian Hope",
      "Death Has No Power Over the Believer",
      "The Resurrection Changes Everything",
      "Living for That Which Will Last",
      "Rewards in Heaven",
      "The New Jerusalem",
    ],
  },
];

// Get a shuffled set of random topics across all categories
export function getRandomTopics(count: number = 12): string[] {
  const all: string[] = [];
  TOPIC_CATEGORIES.forEach(cat => cat.topics.forEach(t => all.push(t)));
  const shuffled = all.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
